UIPBEX-55: Also support feesfines interface version 19.0
folio-org/ui-plugin-bursar-export pull request #103
Opened 2023-10-11 12:25 UTC by Dmitriy-Litvinenko

## Purpose
Also support `feesfines` interface version `19.0`

## Approach
Changes was in endpoint `/accounts` that do not used in current component
This is part of `Quesnelia (R1 2024)` release

## Refs
https://issues.folio.org/browse/UIPBEX-55

2023-10-11 13:03 UTC, ncovercash approved these changes

2023-10-11 13:17 UTC, zburke requested changes
The new `okapiInterface` value looks fine, but the version in the CHANGELOG and in `package.json` do not align so you need to update one or the other. Note that adding support for an interface version is _not_ a breaking change, so this change alone does not force a major version update.

2023-10-11 13:27 UTC, zburke commented
@Dmitriy-Litvinenko , sorry I did not read your PR description ("this is part of Quesnelia (R1 2024) release") in detail. If you want to work on Q features now, that's fine, but you need to bump the version in `package.json` first. It's fine to do that now; when you prepare the P-release, just split a branch from the last commit before the version bump and make the release from that branch:
```
git checkout -b b3.0 <some commit hash>
git push -u origin head
// ... prepare final v3.0.0 CHANGELOG entry etc, and tag the release on a commit on the `b3.0` branch
```

2023-10-12 08:38 UTC, Dmitriy-Litvinenko commented
@zburke Could you please review (package.json updated)? Current pull request will be merged after release previous release.

2023-10-12 20:01 UTC, zburke approved these changes
LGTM. Please make sure when v3.0.0 gets released that you split a `b3.0` branch from the previous commit :)

2023-10-18 11:49 UTC, merged