UIPBEX-53 Implemented TitleManager component
folio-org/ui-plugin-bursar-export pull request #126
Opened 2024-05-14 14:21 UTC by chris-hellen

## Purpose
Added descriptive HTML title to 'Transfer criteria' section of Users settings so that users have easier time navigating multiple pages.

https://folio-org.atlassian.net/jira/software/c/projects/UIPBEX/issues/UIPBEX-53?jql=project%20IN%20%28UIPBEX%2C%20UICAL%29%20ORDER%20BY%20created%20DESC%2C%20status%20DESC

## Approach
Used TitleManager component to implement the descriptive title.

2024-05-14 14:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/folio-org/ui-plugin-bursar-export?pullRequest=126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/folio-org/ui-plugin-bursar-export?pullRequest=126) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/folio-org/ui-plugin-bursar-export?pullRequest=126) it.</sub>

2024-05-14 15:33 UTC, danetsao requested changes
And then looks like some linting issues and one failing test when I tested it locally, so make sure to run tests and lints.

Also, last thing, do you have your formatting set up? When I pulled local, eslint was showing whitespacing errors, may also happen on lint.

2024-05-14 15:33 UTC, danetsao commented on src/BursarExportPlugin.tsx
> +    <TitleManager page={useIntl().formatMessage({ id: "Users settings - Transfer criteria" })}></TitleManager>
To use `useIntl` in this case, you want to have `const intl = useIntl();` at top of file, below `const stripes = useStripes();`. Then you can call `useIntl.formatMessage`.

For `formatMessage`, this takes an id of a string, so you can name it something like `ui-plugin-bursar-export.meta.settingTitle` or smth and then put the string you have right now in the `translations/en.json` file.

And then the `TitleManager` can just wrap the whole thing your returning and you don't need the `<> </>`.

2024-05-15 20:37 UTC, danetsao requested changes
Implementation looks good, but is there a reason you made the `TitleManager` component in this repo? I assume it's bc the `BursarExportPlugin` was not rendering properly, but I investigated and this is bc we have to mock the `TitleManager` component in the jest test. You can do that with something like this I believe.

<img width="1182" alt="Screenshot 2024-05-15 at 3 34 14 PM" src="https://github.com/folio-org/ui-plugin-bursar-export/assets/97154067/eb501b73-8872-4f2a-9c6c-ae5b7ba3a06e">

2024-05-15 20:37 UTC, danetsao commented on src/BursarExportPlugin.tsx
> +    <TitleManager page={intl.formatMessage({ id: 'ui-plugin-bursar-export.meta.settingsTitle' })}>
Implementation looks good here. Although I think you should pass `stripes={stripes}` in as is done in the [ui-cal implementation](https://github.com/folio-org/ui-calendar/pull/502).

2024-05-15 23:19 UTC, chris-hellen commented
Yes, I was having an issue with the bursar plugin rendering. Kept saying that the imports weren't correct, and figured it was because the original "TitleManager" didn't have a specific type since it was JS. I'll try mocking TitleManager with the original implementation. Thanks.

2024-05-16 18:46 UTC, danetsao approved these changes
Looks good to me! I requested review from @ncovercash as well.

2024-05-16 18:48 UTC, ncovercash approved these changes

2024-05-16 18:48 UTC, ncovercash commented on translations/ui-plugin-bursar-export/en.json
> +  "meta.settingsTitle": "Users settings - Transfer criteria",
Meta is special for the settings pane title only - use something else here (title.settings or something)

Doesn't matter as much for this, but still probably would be good

2024-05-16 19:08 UTC, merged